### ISSUE TITLE
Trying to use select_date

### ISSUE THREAD

**Issue by eltonlk** [carlosantoniodasilva/i18n_alchemy#39]
I have a form with the object located, I'm trying to use a select_date, but it gives the error below:

undefined method `change' for "23/07/2015":String

actionview (4.2.3) lib/action_view/helpers/date_helper.rb:832:in `set_day_if_discarded'
actionview (4.2.3) lib/action_view/helpers/date_helper.rb:722:in `select_date'
actionview (4.2.3) lib/action_view/helpers/tags/date_select.rb:14:in `render'
actionview (4.2.3) lib/action_view/helpers/date_helper.rb:258:in `date_select'
actionview (4.2.3) lib/action_view/helpers/date_helper.rb:1070:in `date_select'
simple_form (3.1.0) lib/simple_form/inputs/date_time_input.rb:10:in `input'
simple_form (3.1.0) lib/simple_form/wrappers/leaf.rb:19:in `call'
simple_form (3.1.0) lib/simple_form/wrappers/leaf.rb:19:in `render'
simple_form (3.1.0) lib/simple_form/wrappers/many.rb:28:in `block in render'
simple_form (3.1.0) lib/simple_form/wrappers/many.rb:26:in `each'
simple_form (3.1.0) lib/simple_form/wrappers/many.rb:26:in `render'
simple_form (3.1.0) lib/simple_form/wrappers/root.rb:15:in `render'
simple_form (3.1.0) lib/simple_form/form_builder.rb:115:in `input'
app/views/monthly_payments/_form.html.haml:19:in `block (2 levels) in _app_views_monthly_payments__form_html_haml___3912999882345024763_70273144530800'

have a way to do this?

**Comment by sobrinho** [comment]
@carlosantoniodasilva you can close this due to the lack of activity.

Just for reference, if you are going to use `date_select`, you must do this way:

```ruby
 f.date_select :released_at, selected: @product.released_at
```

In case you don't have the original object, you can use this way (after #50 got merged):

```ruby
 f.date_select :released_at, selected: @localized.unlocalize.released_at
```
